"""Generate stable desktop RPC schemas and TypeScript declarations."""

from __future__ import annotations
import argparse, json
from pathlib import Path
from witness_engine.rpc.models import PROTOCOL_VERSION, RpcErrorEnvelope, RpcRequest, RpcResultEnvelope

ROOT=Path(__file__).resolve().parents[1]
SCHEMA_PATH=ROOT/"contracts"/"json-schema"/"rpc-v1.json"
TS_PATH=ROOT/"contracts"/"generated"/"rpc.ts"
VERSION_PATH=ROOT/"contracts"/"schema-version.txt"

def schema_text() -> str:
    payload={"protocol_version":PROTOCOL_VERSION,"request":RpcRequest.model_json_schema(),"result":RpcResultEnvelope.model_json_schema(),"error":RpcErrorEnvelope.model_json_schema()}
    return json.dumps(payload,indent=2,sort_keys=True)+"\n"

def ts_text() -> str:
    return """// Generated by tools/generate-contracts.py. Do not edit by hand.
export const PROTOCOL_VERSION = 1 as const;
export type SufficiencyState = "SUFFICIENT" | "PARTIAL" | "CONFLICTED" | "INSUFFICIENT";
export interface RpcRequest { v: 1; id: string; method: string; params: Record<string, unknown>; }
export interface RpcError { code: string; message: string; details?: Record<string, unknown> | null; }
export type RpcEnvelope<T> = { v: 1; id: string; type: "result"; result: T } | { v: 1; id: string; type: "error"; error: RpcError };
export interface WorkspaceOpenResult { path:string; database:string; source_versions:number; embedding_provider_id:string; }
export interface SourceVersionSummary { source_version_id:string; logical_source_id:string; source_path:string; title:string; media_type:string; valid_from:string; valid_to:string|null; supersedes_source_version_id:string|null; superseded_by_source_version_id:string|null; }
export interface ContextEvidence { evidence_id:string; chunk_id:string; text:string; source_version_id:string; locator:string|null; method:string; rank:number; }
export interface Citation { evidence_id:string; chunk_id:string; source_version_id:string; locator:string|null; }
export interface AnswerSentence { text:string; evidence_ids:string[]; }
export interface TraceEvent { event_id:string; run_id:string; sequence:number; schema_version:number; stage:string; payload:Record<string,unknown>; created_at:string; }
export interface AskResult {
  run_id:string;
  answer:{state:SufficiencyState;sentences:AnswerSentence[];citations:Citation[]};
  context:{question:string;sufficiency_state:SufficiencyState;sufficiency_reasons:string[];evidence:ContextEvidence[];unresolved_conflicts:Array<{left_evidence_id:string;right_evidence_id:string;reason:string}>};
  retrieval:{candidates:Array<Record<string,unknown>>;trace:Record<string,unknown>};
  reconciliation:Record<string,unknown>;
  sufficiency:{state:SufficiencyState;query_coverage:number;evidence_count:number;independent_source_count:number;unresolved_conflict_count:number;temporal_requirement_satisfied:boolean;reasons:string[]};
  trace:TraceEvent[];
}
export interface GraphNode { id:string; kind:"source"|"entity"|"claim"|"evidence"; label:string; metadata:Record<string,unknown>; }
export interface GraphEdge { id:string; source:string; target:string; relation:string; metadata:Record<string,unknown>; }
export interface GraphSnapshot { nodes:GraphNode[]; edges:GraphEdge[]; }
"""

def main() -> int:
    parser=argparse.ArgumentParser()
    parser.add_argument("--check",action="store_true")
    args=parser.parse_args()
    expected={SCHEMA_PATH:schema_text(),TS_PATH:ts_text(),VERSION_PATH:f"{PROTOCOL_VERSION}\n"}
    if args.check:
        mismatches=[str(p.relative_to(ROOT)) for p,c in expected.items() if not p.exists() or p.read_text(encoding="utf-8")!=c]
        if mismatches:
            raise SystemExit("Generated contracts are stale: "+", ".join(mismatches))
        return 0
    for path,content in expected.items():
        path.parent.mkdir(parents=True,exist_ok=True)
        path.write_text(content,encoding="utf-8")
    return 0

if __name__=="__main__":
    raise SystemExit(main())
