"""Generate stable desktop RPC schemas and TypeScript declarations."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from witness_engine.rpc.models import (
    PROTOCOL_VERSION,
    RpcErrorEnvelope,
    RpcRequest,
    RpcResultEnvelope,
)

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "contracts" / "json-schema" / "rpc-v1.json"
TS_PATH = ROOT / "contracts" / "generated" / "rpc.ts"
VERSION_PATH = ROOT / "contracts" / "schema-version.txt"


def schema_text() -> str:
    payload = {
        "protocol_version": PROTOCOL_VERSION,
        "request": RpcRequest.model_json_schema(),
        "result": RpcResultEnvelope.model_json_schema(),
        "error": RpcErrorEnvelope.model_json_schema(),
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


MULTIMODAL_TS = """export interface VisualRegion { x0:number; y0:number; x1:number; y1:number; }
export interface VisualEvidenceDetail { visual_evidence_id:string; source_version_id:string; modality:"image"|"figure"|"chart"|"table"|"page_region"; page_number:number; region:VisualRegion; locator:string; asset_sha256:string; media_type:string; width_px:number|null; height_px:number|null; label_text:string; }
export interface VisualEvidencePreview { evidence:VisualEvidenceDetail; preview_data_url:string|null; preview_warning:string|null; }

"""


ATTACK_TS = """export interface AttackManifestSummary { manifest_fingerprint:string; attack_id:string; name:string; description:string; mutation_count:number; registered_at?:string; }
export interface AttackInvariantResult { invariant_id:string; kind:string; status:"PASS"|"FAIL"|"NOT_APPLICABLE"; case_id:string|null; detail:string; }
export interface AttackCaseComparison { case_id:string; question:string; clean_state:SufficiencyState|null; attacked_state:SufficiencyState|null; clean_passed:boolean; attacked_passed:boolean; clean_query_run_id:string|null; attacked_query_run_id:string|null; recall_delta:number|null; precision_delta:number|null; citation_coverage_delta:number|null; added_evidence_count:number; removed_evidence_count:number; rank_changed_count:number; clean_answer_text:string; attacked_answer_text:string; }
export interface AttackRunSummary { attack_run_id:string; attack_manifest_fingerprint:string; attack_id:string; attack_name:string; dataset_fingerprint:string; config:EvalConfigInput; canonical_corpus_fingerprint:string; attacked_corpus_fingerprint:string; snapshot_id:string; snapshot_path:string; status:string; started_at:string; completed_at:string|null; }
export interface AttackEvalCaseResult extends Omit<LabCaseDetail,"has_trace"> {}
export interface AttackEvalRunResult { run:EvalRunSummary; cases:AttackEvalCaseResult[]; }
export interface AttackRunResult { run:AttackRunSummary; clean:AttackEvalRunResult; attacked:AttackEvalRunResult; cases:AttackCaseComparison[]; invariants:AttackInvariantResult[]; }
export interface AttackRunListItem { attack_run_id:string; manifest_fingerprint:string; attack_id:string; attack_name:string; dataset_fingerprint:string; canonical_corpus_fingerprint:string; attacked_corpus_fingerprint:string; snapshot_id:string; snapshot_path:string; status:string; started_at:string; completed_at:string|null; }

"""


def ts_text() -> str:
    return "// Generated by tools/generate-contracts.py. Do not edit by hand.\nexport const PROTOCOL_VERSION = 1 as const;\nexport type SufficiencyState = \"SUFFICIENT\" | \"PARTIAL\" | \"CONFLICTED\" | \"INSUFFICIENT\";\nexport type RetrievalMode = \"lexical\" | \"dense\" | \"hybrid\" | \"routed\";\nexport interface RpcRequest { v:1; id:string; method:string; params:Record<string,unknown>; }\nexport interface RpcError { code:string; message:string; details?:Record<string,unknown>|null; }\nexport type RpcEnvelope<T> = {v:1;id:string;type:\"result\";result:T}|{v:1;id:string;type:\"error\";error:RpcError};\nexport interface WorkspaceOpenResult { path:string; database:string; source_versions:number; embedding_provider_id:string; visual_embedding_provider_id:string; }\nexport interface SourceVersionSummary { source_version_id:string; logical_source_id:string; source_path:string; title:string; media_type:string; valid_from:string; valid_to:string|null; supersedes_source_version_id:string|null; superseded_by_source_version_id:string|null; }\nexport interface ContextEvidence { evidence_id:string; chunk_id:string; text:string; source_version_id:string; locator:string|null; method:string; rank:number; evidence_kind:string; visual_evidence_id:string; modality:string; }\nexport interface Citation { evidence_id:string; chunk_id:string; source_version_id:string; locator:string|null; evidence_kind:string; visual_evidence_id:string; modality:string; }\nexport interface AnswerSentence { text:string; evidence_ids:string[]; }\nexport interface TraceEvent { event_id:string; run_id:string; sequence:number; schema_version:number; stage:string; payload:Record<string,unknown>; created_at:string; }\nexport interface AskResult {\n  run_id:string;\n  answer:{state:SufficiencyState;sentences:AnswerSentence[];citations:Citation[]};\n  context:{question:string;sufficiency_state:SufficiencyState;sufficiency_reasons:string[];evidence:ContextEvidence[];unresolved_conflicts:Array<{left_evidence_id:string;right_evidence_id:string;reason:string}>};\n  retrieval:{candidates:Array<Record<string,unknown>>;trace:Record<string,unknown>};\n  reconciliation:Record<string,unknown>;\n  sufficiency:{state:SufficiencyState;query_coverage:number;evidence_count:number;independent_source_count:number;unresolved_conflict_count:number;temporal_requirement_satisfied:boolean;reasons:string[]};\n  trace:TraceEvent[];\n}\nexport interface GraphNode { id:string; kind:\"source\"|\"entity\"|\"claim\"|\"evidence\"; label:string; metadata:Record<string,unknown>; }\nexport interface GraphEdge { id:string; source:string; target:string; relation:string; metadata:Record<string,unknown>; }\nexport interface GraphSnapshot { nodes:GraphNode[]; edges:GraphEdge[]; }\n\nexport interface EvalDatasetSummary { dataset_fingerprint:string; dataset_id:string; name:string; description:string; case_count:number; registered_at:string; }\nexport interface EvalConfigInput { name:string; retrieval_mode:RetrievalMode; top_k:number; candidate_pool:number; rerank_pool:number; rrf_k:number; rerank:boolean; chunk_max_chars:number; }\nexport interface EvalConfigSnapshot extends EvalConfigInput { config_id:string; corpus_fingerprint:string; embedding_provider_id:string; reranker_provider_id:string; generator_provider_id:string; visual_embedding_provider_id:string|null; }\nexport interface EvalRunMetrics { objective:Record<string,number>; model_judged:Record<string,number>; case_count:number; passed_cases:number; failed_cases:number; total_latency_ms:number; mean_latency_ms:number; p95_latency_ms:number; total_cost_usd:number|null; cost_available:boolean; }\nexport interface EvalRunSummary { run_id:string; dataset_fingerprint:string; dataset_id:string; dataset_name:string; config:EvalConfigSnapshot; status:string; started_at:string; completed_at:string|null; metrics:EvalRunMetrics|null; }\nexport interface EvalCaseMetrics { recall_at_k:number|null; precision_at_k:number|null; reciprocal_rank:number|null; ndcg_at_k:number|null; citation_precision:number|null; citation_coverage:number|null; unsupported_claim_rate:number|null; abstention_correct:boolean|null; contradiction_handling_correct:boolean|null; state_correct:boolean|null; answer_contains_correct:boolean|null; latency_ms:number; cost_usd:number|null; cost_available:boolean; matched_gold_count:number; gold_count:number; retrieved_count:number; passed:boolean; failure_reasons:string[]; }\nexport interface EvalCaseSummary { case_id:string; question:string; query_run_id:string|null; answer_state:SufficiencyState|null; metrics:EvalCaseMetrics; error:string|null; has_trace:boolean; }\nexport interface LabRunResult { run:EvalRunSummary; cases:EvalCaseSummary[]; }\nexport interface LabCaseDetail extends Omit<EvalCaseSummary,\"has_trace\"> { ask_result:AskResult|null; }\nexport interface LabMetricComparison { metric:string; a:number|null; b:number|null; delta:number|null; kind:\"objective\"; }\nexport interface LabCaseComparison { case_id:string; question:string; a_passed:boolean; b_passed:boolean; a_state:SufficiencyState|null; b_state:SufficiencyState|null; a_query_run_id:string|null; b_query_run_id:string|null; a_failures:string[]; b_failures:string[]; }\nexport interface LabComparison { dataset_fingerprint:string; dataset_id:string; dataset_name:string; run_a:EvalRunSummary; run_b:EvalRunSummary; metrics:LabMetricComparison[]; model_judged_metrics:Array<Record<string,unknown>>; cases:LabCaseComparison[]; failed_cases:LabCaseComparison[]; }\n\n" + MULTIMODAL_TS + ATTACK_TS


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = {
        SCHEMA_PATH: schema_text(),
        TS_PATH: ts_text(),
        VERSION_PATH: f"{PROTOCOL_VERSION}\n",
    }
    if args.check:
        mismatches = [
            str(path.relative_to(ROOT))
            for path, value in expected.items()
            if not path.exists()
            or path.read_text(encoding="utf-8") != value
        ]
        if mismatches:
            raise SystemExit(
                "Generated contracts are stale: " + ", ".join(mismatches)
            )
        return 0
    for path, value in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(value, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
